### ISSUE TITLE
my game crashes 

### ISSUE THREAD

**Issue by sarcotix** [RED1cat/SkyCoopInstaller#1]
every time I open the long dark with the mod installed, only happening since new update and I've tried fresh reinstalls 
![image](https://user-images.githubusercontent.com/79560310/212488457-13bf70c1-87df-407d-ab83-e47f2c570743.png)
![image](https://user-images.githubusercontent.com/79560310/212488461-668a96fa-e09c-47ef-9c9e-6a5fffc1c658.png)

**Comment by NadineLaakso** [comment]
Same here, checked for correct file path and installed the perilous constraint version. Any hints on what to do differently would be appreciated.

**Comment by Filigrani** [comment]
No logs provided. Also it looks like you installed mod on incorrect version of the game. Downgrade game to 2.01
