### ISSUE TITLE
Doesnt seem to function with the current version of the game

### ISSUE THREAD

**Issue by problemlow** [RED1cat/SkyCoopInstaller#2]
My friends client crashes when he tries to use it and mine opens but the multiplayer menu is missing hope this helps. I also dont have any dlc hope that help. Heres my log file
[MelonLoader_23-08-09_17-57-46.169.log](https://github.com/RED1cat/SkyCoopInstaller/files/12305085/MelonLoader_23-08-09_17-57-46.169.log)

**Comment by ljans** [comment]
What exactly do you mean by "current version" of the game? The Sky Co-op mod only works with game version 2.01 and 2.02.

**Comment by problemlow** [comment]
I mean 2.19. Depending on what exactly stops it from working with the current version I could take a crack at updating it, though im more of a python/js man myself. Is it in full rework territory or just a few annoying things that need redoing?

**Comment by ljans** [comment]
As far as I understand, Hinterland introduced a breaking change after version 2.02 that made every mod stop working from a fundamental standpoint. I wouldn't expect Sky Co-op to function on a higher version than 2.02 any time soon.
If you own the game on Steam, you can follow the instructions on [this page](https://www.thelongdark.com/time-capsule/perilous-constraint/) to downgrade.
